### ISSUE TITLE
ModuleNotFoundError: No module named 'feedparser'

### ISSUE THREAD

**Issue by roughnecks** [deltachat-bot/rss_bot#1]
I get this while `pip install`

https://paste.debian.net/hidden/6608d856/

**Comment by roughnecks** [comment]
I can manually `pip install feedparser` and all the other needed modules but when I run:

`deltabot init mail pwd`

I get:
`-bash: !3: event not found`

**Comment by roughnecks** [comment]
> I get:
> `-bash: !3: event not found`

I think that's my password containing a "!" because I had the same issue with delta chat faqbot.
So, I believe only the setup part is broken.

**Comment by roughnecks** [comment]
Now that I've changed password, I'm getting this at `deltabot init`:

```
Traceback (most recent call last):
  File "/home/bots/DC-rss-bot/venv/bin/deltabot", line 8, in <module>
    sys.exit(main())
  File "/home/bots/DC-rss-bot/venv/lib/python3.9/site-packages/deltabot/main.py", line 14, in main
    pm = get_global_plugin_manager()
  File "/home/bots/DC-rss-bot/venv/lib/python3.9/site-packages/deltabot/plugins.py", line 40, in get_global_plugin_manager
    _pm = make_plugin_manager()
  File "/home/bots/DC-rss-bot/venv/lib/python3.9/site-packages/deltabot/plugins.py", line 57, in make_plugin_manager
    pm.load_setuptools_entrypoints("deltabot.plugins")
  File "/home/bots/DC-rss-bot/venv/lib/python3.9/site-packages/pluggy/_manager.py", line 287, in load_setuptools_entrypoints
    plugin = ep.load()
  File "/usr/lib/python3.9/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'rss_bot'
```

**Comment by roughnecks** [comment]
```
pip install rss-bot
Requirement already satisfied: rss-bot in ./venv/lib/python3.9/site-packages (0.1.1)
Requirement already satisfied: html2text in ./venv/lib/python3.9/site-packages (from rss-bot) (2020.1.16)
Requirement already satisfied: deltabot>=0.7.3 in ./venv/lib/python3.9/site-packages (from rss-bot) (0.8.0)
Requirement already satisfied: beautifulsoup4 in ./venv/lib/python3.9/site-packages (from rss-bot) (4.11.2)
Requirement already satisfied: sqlalchemy>=1.3.0 in ./venv/lib/python3.9/site-packages (from rss-bot) (2.0.6)
Requirement already satisfied: feedparser>=5.1.1 in ./venv/lib/python3.9/site-packages (from rss-bot) (6.0.10)
Requirement already satisfied: py in ./venv/lib/python3.9/site-packages (from deltabot>=0.7.3->rss-bot) (1.11.0)
Requirement already satisfied: deltachat>=1.40.1 in ./venv/lib/python3.9/site-packages (from deltabot>=0.7.3->rss-bot) (1.111.0)
Requirement already satisfied: requests in ./venv/lib/python3.9/site-packages (from deltachat>=1.40.1->deltabot>=0.7.3->rss-bot) (2.28.2)
Requirement already satisfied: imap-tools in ./venv/lib/python3.9/site-packages (from deltachat>=1.40.1->deltabot>=0.7.3->rss-bot) (1.0.0)
Requirement already satisfied: cffi>=1.0.0 in ./venv/lib/python3.9/site-packages (from deltachat>=1.40.1->deltabot>=0.7.3->rss-bot) (1.15.1)
Requirement already satisfied: pluggy in ./venv/lib/python3.9/site-packages (from deltachat>=1.40.1->deltabot>=0.7.3->rss-bot) (1.0.0)
Requirement already satisfied: pycparser in ./venv/lib/python3.9/site-packages (from cffi>=1.0.0->deltachat>=1.40.1->deltabot>=0.7.3->rss-bot) (2.21)
Requirement already satisfied: sgmllib3k in ./venv/lib/python3.9/site-packages (from feedparser>=5.1.1->rss-bot) (1.0.0)
Requirement already satisfied: typing-extensions>=4.2.0 in ./venv/lib/python3.9/site-packages (from sqlalchemy>=1.3.0->rss-bot) (4.5.0)
Requirement already satisfied: greenlet!=0.4.17 in ./venv/lib/python3.9/site-packages (from sqlalchemy>=1.3.0->rss-bot) (2.0.2)
Requirement already satisfied: soupsieve>1.2 in ./venv/lib/python3.9/site-packages (from beautifulsoup4->rss-bot) (2.4)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in ./venv/lib/python3.9/site-packages (from requests->deltachat>=1.40.1->deltabot>=0.7.3->rss-bot) (1.26.15)
Requirement already satisfied: certifi>=2017.4.17 in ./venv/lib/python3.9/site-packages (from requests->deltachat>=1.40.1->deltabot>=0.7.3->rss-bot) (2022.12.7)
Requirement already satisfied: idna<4,>=2.5 in ./venv/lib/python3.9/site-packages (from requests->deltachat>=1.40.1->deltabot>=0.7.3->rss-bot) (3.4)
Requirement already satisfied: charset-normalizer<4,>=2 in ./venv/lib/python3.9/site-packages (from requests->deltachat>=1.40.1->deltabot>=0.7.3->rss-bot) (3.1.0)
```

**Comment by missytake** [comment]
Hm, this bot isn't really maintained - does https://github.com/simplebot-org/simplebot_feeds work for you? It's actually a lot better than this one.

If you need this one for something, I can dive deeper into the issue :) didn't touch the code in more than 2 years tbh.

**Comment by roughnecks** [comment]
Yeah, I can try simplebot_feeds, not big deal!

Thanks
